name = "SloanUGRIZFilters"
uuid = "9ca1ba71-c229-46e3-8ae9-21d24b118006"
authors = ["Nikos Gianniotis"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
